---
title: "ModelJudgment"
author: "Julia"
date: "2023-12-02"
output: html_document
---

# Step 3: Load datas
```{r}
library(readxl)
library(tidyverse)
sheet_names <- c("Overall", "Smit Judgements", "Julia Judgements", "Freya Judgements", "Leo Judgements")
path <- "E:/MQM_Courses/Term3/Intermediate finance/Intermediate_Finance/CriticalThinking/predictions.xlsx"
Greg <- read_excel(path, sheet = sheet_names[1]) %>% arrange(Institution)
Smit <- read_excel(path, sheet = sheet_names[2])[,1:17] %>% arrange(Institution)
Julia <- read_excel(path, sheet = sheet_names[3]) %>% arrange(Institution)
Freya <- read_excel(path, sheet = sheet_names[4]) %>% arrange(Institution)
Leo <- read_excel(path, sheet = sheet_names[5]) %>% arrange(Institution)

orig.datas <- list(Greg,Smit,Julia,Freya,Leo)
orig.datas[2]
```

```{r}
FreyaLM
GregLM <- lm(Greg~., data = Greg)
SmitLM <- lm(Smit~.,data = Smit)
JuliaLM <- lm(Julia~.,data = Julia)
FreyaLM <- lm(Freya~.,data = Freya)
LeoLM <- lm(Leo~.,data=Leo)
lmlist <- list(GregLM,SmitLM,JuliaLM, FreyaLM,LeoLM)
lmsums <- list(summary(GregLM),summary(SmitLM),summary(JuliaLM), summary(FreyaLM), summary(LeoLM))
pval <- 0.05
members <- c("Greg ~ ", "Smit ~ ", "Julia ~ ", "Freya ~ ", "Leo ~ ")
newLM <- list()
fit.resid <- list()
for (i in seq(1,3)){
  Var = rownames(lmsums[[i]]$coefficients)[lmsums[[i]]$coefficients[,4] < pval]
  formula_str <- as.formula(paste(members[i], paste(Var[Var != "(Intercept)"], collapse = " + ")))
  lm.n = lm(formula_str, data = orig.datas[[i]])
  newLM[i] = lm.n
  resids = lm.n$residuals
  fits = lm.n$fitted.values
  newdata <- data.frame(predicts = orig.datas[[i]][, 17], fits = fitted(lm.n), resids = resid(lm.n))
  fit.resid[[i]] <- newdata
}

rownames(lmsums[[4]]$coefficients)[lmsums[[4]]$coefficients[,4] < pval]
lm.n.f <- lm(Freya~Region, data = orig.datas[[4]])
newLM[4] <- lm.n.f
rownames(lmsums[[5]]$coefficients)[lmsums[[5]]$coefficients[,4] < pval]
lm.n.l <- lm(Leo~size+Asian, data = orig.datas[[5]])
newLM[5] <- lm.n.f
newdata <- data.frame(predicts = orig.datas[[4]][, 17], fits = fitted(lm.n.f), resids = resid(lm.n.f))
fit.resid[[4]] <- newdata
newdata <- data.frame(predicts = orig.datas[[5]][, 17], fits = fitted(lm.n.l), resids = resid(lm.n.l))
fit.resid[[5]] <- newdata

newLM[[1]]
newLM[[3]]
fit.resid[[4]]
```

# Step 6: Predictability of the judge, Rs
```{r}
Rs = NULL
for (i in seq(1,length(fit.resid))){
  data = fit.resid[i]
  corr = cor(fit.resid[[i]][,1],fit.resid[[i]][,2])
  Rs[i] = corr
}
round(Rs,4)
```

# Step 7: Load data
```{r}
salaries <- read_excel("E:/MQM_Courses/Term3/Intermediate finance/Intermediate_Finance/CriticalThinking/salaries.xlsx")
```

# Step 8: Judge achievement, Ra
```{r}
Ra = NULL
for (i in seq(1,length(fit.resid))){
  data = fit.resid[[i]]
  corr = cor(data[,1],salaries[,2])
  Ra[i] = corr
}
Ra
```

# Step 9: Bootstrap model achievement, Rm
```{r}
Rm = NULL
for (i in seq(1,length(fit.resid))){
  data = fit.resid[[i]]
  corr = cor(data[,2],salaries[,2])
  Rm[i] = corr
}
Rm
```
# Step 10: Rm > Ra?
```{r}
Rm > Ra
```

# Step 11: Residual Intuition, Rz

```{r}
Rz = NULL
for (i in seq(1,length(fit.resid))){
  data = fit.resid[[i]]
  corr = cor(salaries[,2], data[,3])
  Rz[i] = corr
}
Rz
```
```{r}
c(Rs[3],Ra[3], Rm[3], Rz[3])

```
















