---
title: "Case1"
author: "Julia"
date: "2023-11-07"
output: html_document
---
```{r}
library(ggplot2)
library(PortfolioAnalytics)
library(writexl)
library(tidyverse)
```


# loading data
```{r}
load("./A.RData")
load("./B1.RData")
load("./B2.RData")
```

# PART A

```{r try}
# 1. mean and sd
meanSD <- data.frame(
  ERi = apply(nominal[-1], 2, mean),
  SDi = apply(nominal[-1], 2, sd))
otherAssets <- meanSD[5:6,]
meanSD <- meanSD[1:4,]
# 2. correlation
correlation <- cor(nominal[-1])[1:4,1:4]
# 3. covariance
covariance <- cov(nominal[-1])[1:4,1:4]
```

```{r try}
library(tseries)

n_portfolios <- 100
set.seed(1234)
all_weights <- matrix(nrow = n_portfolios, ncol = 4)

for (i in 1:n_portfolios){
  weights <- runif(4)
  weights <- weights/ sum(weights)
  all_weights[i,] <- weights
}

portfolio_Rsd <- data.frame(
  return = rowSums(meanSD$ERi*all_weights),
  sd =  sqrt(rowSums(all_weights %*% (covariance %*% t(all_weights))))
)

return_levels = seq(from = 0, to = 1, length.out = n_portfolios)
results <- data.frame(Return = numeric(), Risk = numeric(), Portfolio = list())

for (target_return in return_levels){
  result <- portfolio.optim(x = as.matrix(nominal)[,2:5], covmat = covariance, target = target_return)
  risk <- result$ps
  portfolio <- result$pw
  results <- rbind(results, data.frame(Return = target_return, Risk = risk, Portfolio = portfolio))
}

ggplot(results, aes(x = Risk, y = Return)) +
  geom_point() +
  labs(title = "Mean-Standard Deviation Frontier", x = "Standard Deviation (Risk)", y = "Expected Return")
```


```{r plot}
library(readxl)
frontier <- read_excel("./nominal.xlsx", sheet = "frontier")
port7 <- read_excel("./nominal.xlsx", sheet = "port7")
names(port7) <- names(frontier)
frontier <- rbind(frontier, port7[1:2,])
frontier <- frontier %>%
  mutate(MSR = case_when(
    Target == "MSR" ~ "MSR",
    Target == "GMV" ~ "GMV",
    TRUE ~ "Other"
  ))
# efficient frontier
ggplot()+
  geom_point(data = frontier, aes(x = SD, y = Return, color = MSR))

```


# PART B1

```{r}
MeanSD <- data.frame(
  return = B1$mean,
  sd = B1$sd
)
rownames(MeanSD) <- c("short-term bonds", "medium-term bonds", "long-term bonds", "Canadian equity", "US equity", "non-North American equity")
```
```{r}
library(readxl)
frontier <- read_excel("./nominal.xlsx", sheet = "g")
ggplot(data = frontier)+
  geom_point(aes(x = Variance, y = Return))+
  geom_abline(slope = (0.033300027-meanSD$ERi[6])/sqrt(0.365148237), intercept = meanSD$ERi[6])
```














